### ISSUE TITLE
How to specify .cer provided by SAML provider as in a string variable?

### ISSUE THREAD

**Issue by GIParekh** [jitbit/AspNetSaml#12]
I have been provided tokensigning.cer file by SAML provider. How can I use it to specify the certificate in string variable as mentioned in set 2 code as below:

`//specify the certificate that your SAML provider has given to you
            string samlCertificate = @"-----BEGIN CERTIFICATE-----
BLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAHBLAH123543==
-----END CERTIFICATE-----";`

**Comment by erenes** [comment]
I converted my certificate to base64 and created a new constructor for Saml.Response that takes that: 
```
var samlCert = Convert.FromBase64String("MIIFxTC..."); 
Response r = new Response(samlCert);
```

The constructor: 
```
    public Response(byte[] certificateBytes)
    {
      RSAPKCS1SHA256SignatureDescription.Init(); //init the SHA256 crypto provider (for needed for .NET 4.0 and lower)

      _certificate = new Certificate();
      _certificate.LoadCertificate(certificateBytes);
    }
```

**Comment by alex-jitbit** [comment]
@erenes  plz send us a pull-request with the overloaded constructor?

**Comment by alex-jitbit** [comment]
@erenes thanks!!!
