### ISSUE TITLE
authnrequest signing support?

### ISSUE THREAD

**Issue by mrtristan** [jitbit/AspNetSaml#15]
As you can guess by the title, wondering if there are plans or thoughts on an approach for signing requests to the idp?

sorry for duping https://github.com/jitbit/AspNetSaml/issues/4 but that one was closed

**Comment by alex-jitbit** [comment]
No plans yet, and TBH I don't even know where to start

**Comment by mrtristan** [comment]
thanks for the quick response. it looks like i'm going to implement another `AuthRequestFormat` option or something along those lines and go for it.

in my implementation of what you're doing here, i've really ripped it apart and broken it up in to sep. files and (in my mind) improved the formatting and things of that nature. i think i also added other methods of loading certs. would that be too much of a pull request if i were to send that to you? i'd probably wrap it in a project that's easily nuget'able and such too.

beyond (perhaps) a namespace change, i don't believe there are any breaking changes

**Comment by alex-jitbit** [comment]
is there some place I can review the changes? like on github or something... And then I will move them here manually

**Comment by mrtristan** [comment]
yeah i'll do something along those lines. seemingly almost done

**Comment by mrtristan** [comment]
@alex-jitbit 

wound up on other projects and such over the last month. back to having some time to finalize what i was doing.

the master branch here is currently being tested against a decent sized company's microsoft-based idp. signing is working well. i also have started work for signed authn posts. i wound up not needing that for this particular implementation but didn't want to throw it away so it's in a branch. just needs some testing.

i have a few housekeeping tasks remaining like updating the readme and pushing to nuget. the latter i won't do if you're interested in merging this. i'm just assuming it's too much of a deviation from the direction you were going.

i plan on also needing to implement encryption functionality so that'll be coming at some point.

https://github.com/mrtristan/CoreSaml2Utils

thoughts?

Edit: wound up needing assertion decryption, so added that.

**Comment by boney0002** [comment]
Is there any update on this issue? I'd like to use this library, but need to be able to send signed requests.
