### ISSUE TITLE
ADFS SAML configuration

### ISSUE THREAD

**Issue by ChetanChaudhari03** [jitbit/AspNetSaml#16]
Hi,

Im using same lib but when i deploy my application in IIS  and hits defalut.aspx page its redirect my page to ADFS page but ADFS page gives error.
Error as below:
An error occurred 
An error occurred. Contact your administrator for more information. 
•	Activity ID: 00000000-0000-0000-e934-0080060000f8
•	Error time: Mon, 04 Mar 2019 05:30:06 GMT
•	Cookie: enabled
•	User agent string: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

So can you help me for **How to configure ADFS SAML in AD server with steps?**

Thanks,
Chetan

**Comment by cronuslear** [comment]
Did you find a solution? I met the same issue. Thx
