### ISSUE TITLE
Response.Redirect in mvc

### ISSUE THREAD

**Issue by ShanghaiBill** [jitbit/AspNetSaml#18]
I am attempting to implement AspNetSaml in mvc but ran into an error. The Response.Redirect line in step 1 of your example gives an error that says it doesn't exist in the current context. I have placed the code into the StartUp.cs page of the application replacing the app.UseAuthentication() method. 
How do I do a redirect to my provider in mvc and am I placing the code in the correct place?

Thanks

**Comment by alex-jitbit** [comment]
It should be in an action-method, not in "Startup"
