### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by GregGohl** [jitbit/AspNetSaml#21]
Hi, I tried using your code, but I don't know MVC.  So, i put it on a consume.aspx page, in the Page_Load.  
Anyhow, i'm getting Object reference not set to an instance of an object when it gets to this part of the code:
Saml.Response samlResponse = new Response(samlCertificate, Request.Form["SAMLResponse"]);

I'm not sure if what i'm doing wrong is the MVC part of it, the samlCertificate, or something else,or all of the above.
Here is the code.  Thanks for any help.

`protected void Page_Load(object sender, EventArgs e)
        {`
           ` try
            {`
                `string samlCertificate = @"MIIDvTCCAqWgAwIBAgIQS1+YLCdzuulaz9PgVXaUZYjANBgkqhkiG9w0BAQsFADBoMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEQMA4GA1UECgwHWnNjYWxlcjEyMDAGA1UEAwwpRVQg
enBhYmV0YS5uZXQgSW50ZXJtZWtRpYXRlIENlcnRpZmljYXRlIDIwHhcNMTkwMTE4MDY0MTAxWhcN
MjEwMTE3MDY0MTAxWjBSMQswCQeYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEQMA4GA1UE
CgwHWnNjYWxlcjEcMBoGA1UEAwxwTc2FtbHNwMS56cGFiZXRhLm5ldDCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALRBEMWTtgQw//PxoubAum3fTakGQNk2C8/WsG+zr3ouETVg3AJFcU49l
W6PvzMyq9ySNZouGtI2OraLLdisyo3qkUFluMXCT5nSZ6mxFQ+pYzASCFwc6BwLKSBZioUL8/FkLp
LbQgSGNqwH0c8Zgm+Ys0Yc3CqAtkgO/kVsJfyD7Aj5lGas7EmXB1lVbGfELzKEXSNXQgR4lFVF7PF
1MgFontEECKHKYITny+gohtnzulTsy+UE8SvBes6uR69EZAwGQ88KwZ3GLsS+mhFqxdrflHzom1rj
QaHf44FnqBFRX6tcd3QbOggR77sTAFC6fHY1vgYtT4eDiKIa8LMYCNv9vrFMCAwEAAaN5MHcwCQYD
VR0TBAIwADALBgNVHQ8EBAMCBadAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1Ud
DgQWBBSUgr1Me29VPEtICrxnOitbjhIspMzAfBgNVHSMEGDAWgBThF4kFL8wt78YK/4VWAM5/Zyr2
aTANBgkqhkiG9w0BAQsFAAOCAQEAjqkavdpcvsyv+4exf0mzqvCOTpDSKSKqgD4uZBrPFwsOfU8ma
k3JyVqEde7vZPcvL9md0rpUqFFiqfeApqRKN2FEEsdrK2CUrr1NRVk/vB1vm/wMJ60KcF/coAUo7M
+WamSdyEsY9ApHu3/oP4fKX6/kbUgn2s5dt+DhGH2YvoDUquToDXYJ4uEM+PKMs1/Ns7alCGbBR16
N51dH+bW6Jq+uBcNhlv4HHSD2xQtWoimf6xQLAtod7VVFyIh/8N0eakQ9CutV0Bsq6F6/jwb+gEiH
ljnzutyWDyh0a+5OQj6ULQkKYyK4r8UozOKBC5b5Rq3yVt2Q5FZgYe2j1hJGXsxAKQ==";`
              
  `Saml.Response samlResponse = new Response(samlCertificate, Request.Form["SAMLResponse"]);`

                if (samlResponse.IsValid())
                {
                    Label1.Text = "WOOHOO!!! user is logged in";
                    string username, email, firstname, lastname;
                    try
                    {
                        username = samlResponse.GetNameID();
                        Label2.Text = "user eid is:" + username;
                    }

                    catch (Exception ex)
                    {
                    }
                    finally
                    {
                    }
       
                }
                else
                {
                }
           
            }
            catch (Exception ex)
            {
          
            }
            finally
            {
               
            }
        }`

**Comment by alex-jitbit** [comment]
This exception means the "SAMLReponse" `POST` parameter hasn't been passed to your script.

**Comment by GregGohl** [comment]
I figured out why it wasn't working for me. Posting this if anybody else has the same problem.   I had it in Page_Load.  I changed to OnLoad see below:
protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            try
            {
                blah blah blah 
            }
}

and it worked.
Thanks again so much for your SAML code.
