### ISSUE TITLE
Can I use this library for G suite SSO?

### ISSUE THREAD

**Issue by ce51benz** [jitbit/AspNetSaml#22]
As the title say. I want to ask that does this library support SSO to Google suite? Because I am looking for simple SAML2 library to use in my web application. I want only SSO login and get attributes of user only.

**Comment by alex-jitbit** [comment]
Yes you can, we have an article published on our website, part of it describes how to get certificate and other settings form google

https://www.jitbit.com/hosted-helpdesk/saml-google/

**Comment by ce51benz** [comment]
Wow! Very good article. I never found this useful information. Thank you very much for your answer. I just used this simple library today. It's very simple library. I can read and understand in short time. (With pre-knowledge of SAML 2.0)

**Comment by ce51benz** [comment]
May I ask another question? If user already logged in, how SP know that and allow user to go to protect resources. Can you give me some advice? My idea on this issue is SP make SAML request to IDP everytime via back-channel to check it.
