### ISSUE TITLE
Redirect URL in saml response

### ISSUE THREAD

**Issue by viveknatani** [jitbit/AspNetSaml#23]
We're building an MVC 5 app and utilizing the SSO with this AspNetSaml. Everything appears to work but I was just wondering if I can find out the Redirect URL when the assertionConsumerServiceUrl is called. This is to redirect the user back (after the successful authentication) to the same page that user initially navigated to instead of the app landing page. 

Please advise.

**Comment by alex-jitbit** [comment]
We don't have built-in feature for that, you would have to do that yourself. For example save it to the session or pass via query string.
