### ISSUE TITLE
Logout request with specific redirect url

### ISSUE THREAD

**Issue by wan-liyang** [jitbit/AspNetSaml#25]
Hi, may i have your help about how to build a saml logout request to sign out the account, after sign out success, redirect to specific page of the application?

**Comment by alex-jitbit** [comment]
Do you mean service provider initiated logout or indentity provider initiated logout?

(service provider is your app, ID provider is the SAML provider)

**Comment by wan-liyang** [comment]
hi alex, when perform logout action from my app, it will do session & cookie clean, if do not close browser, then perform login action again, browser will remeber previous azure AD account, so i think there should be one action to sign out the azure AD, but the problem is after sign out the azure AD via call speicific URL, how it redirect back to the specific page of my app? because want to show some customized information.

**Comment by AnthonyVO** [comment]
I would also like to implement a service provided logout.  From my research this will require a digitally signed message.

**Comment by fatbigbright** [comment]
I've submitted a [pull request#48](https://github.com/jitbit/AspNetSaml/pull/48) to support signing out request to IDP and get the response returned.

Please check whether it can be merged into the main branch.
