### ISSUE TITLE
License Confusion?

### ISSUE THREAD

**Issue by AnthonyVO** [jitbit/AspNetSaml#26]
The saml.cs file appears to have a MIT license at the top which I greatly prefer.

But the License file in the project is Apache License Version 2.0, January 2004

Just checking which it actually is.

Thanks.

**Comment by ngcdev** [comment]
Hi!

Same here! I've been using the library for a while now and in the source code it says MIT license. But the newly added file says Apache, and I was just put in charge of finding all of the licenses of all of the components we're using.

Thanks

**Comment by alex-jitbit** [comment]
Sorry about the confusion. The license is Apache b/c it is as permissive as MIT, but also protects **_you_** from patent trolls - therefore more "big" companies are willing to use Apache than MIT. I'll update the sources.
