### ISSUE TITLE
Implementing SSO on button click

### ISSUE THREAD

**Issue by sarveshgupta1993** [jitbit/AspNetSaml#28]
Hi Alex,

I saw your code , and same implementation is done is at my company side ,I need your help ,there is a requirement ,we have one typescript/html page where we are showing two radio buttons  ,on click of that I have to hit particular IDP Url's  (we have two IDP Url's) , could you modified your code and let me know how to achieve this ,On success callback (typescript) after authentication ,setting up session ,I have to redirect to Dashboard page .I could not find any useful article with my scenario

**Comment by alex-jitbit** [comment]
Not sure I follow, this is for C#, server-side, not typescript
