### ISSUE TITLE
[Question] Single Logout

### ISSUE THREAD

**Issue by nelfer** [jitbit/AspNetSaml#3]
Hi,
Do you have a way to manage the single logout?

https://developers.onelogin.com/saml/examples/logout-request

I tried to create the request (following your example) but then it has to be signed and I don't know how to do that (I was trying to do the HTTP-Redirect)

**Comment by jitbit** [comment]
Sorry, it currently has no way of sending a "logout" request.

I don't think its gonna work with redirect, you have to send POST data to the provider server.
