### ISSUE TITLE
Sample code issue with Response function

### ISSUE THREAD

**Issue by rvernon9** [jitbit/AspNetSaml#30]
In the sample code provided, it includes this line:
`Saml.Response samlResponse = new Response(samlCertificate, Request.Form["SAMLResponse"]);`

However, the code for the function "Response" only contains one parameter, not two. Is the sample code in error or is the code within the "Saml.cs" file incorrect?

Thanks

**Comment by rvernon9** [comment]
After investigating, I found that the "Saml.cs" file that I got from NuGet was not the same as the "Saml.cs" file found in this site. The "Saml.cs" file in this website has code that corresponds with the sample code usage provided.

**Comment by cessna** [comment]
I noticed the same thing. The NuGet package isn't in sync with the GitHub version.

**Comment by alex-jitbit** [comment]
I'll update the nuget shortly

**Comment by alex-jitbit** [comment]
fixed in 9f31df71ba6585bb679c51c70c46f67358c668f8
