### ISSUE TITLE
What should go into the "Issuer" field?

### ISSUE THREAD

**Issue by chtenb** [jitbit/AspNetSaml#37]
In the sample code when creating a authentication request, the issuer is set to the application URL.

```cs
	var request = new AuthRequest(
		"http://www.myapp.com", //TODO: put your app's "unique ID" here
		"http://www.myapp.com/SamlConsume" //TODO: put Assertion Consumer URL (where the provider should redirect users after authenticating)
		);
```

I've noticed that when I leave this empty, everything seems to "just work". What is the purpose of this field?

**Comment by alex-jitbit** [comment]
It's an informational field that defines your app uniquely. It might work, but it makes it hard to look through the logs afterwards.

**Comment by chtenb** [comment]
Thanks!

**Comment by chtenb** [comment]
This is also commonly referred to as "entity ID", correct?

**Comment by alex-jitbit** [comment]
Yes, correct. We should probably rename that field to remove confusion
