### ISSUE TITLE
Compile error in saml.cs in Init method

### ISSUE THREAD

**Issue by huseinshaikh** [jitbit/AspNetSaml#39]
I am using .net framework 3.5

public static void Init()
		{
            if (!_initialized)
                CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
            _initialized = true;           
		}
CryptoConfig.AddAlgorithm is not found, may be because I am using lower version of .net frame work.
Can you suggest what can be work around for this.

**Comment by alex-jitbit** [comment]
Yep, it appears it's only in .NET 4.0, not sure if there are any workarounds for .NET 3.5 sorry
