### ISSUE TITLE
ACS URL is ignored by IdP

### ISSUE THREAD

**Issue by chtenb** [jitbit/AspNetSaml#40]
All IdPs I've come across so far require a hardconfigured ACS URL to be set in the IdP setup.
The ACS passed in the Authentication request by seems to be completely ignored. Is this expected behavior, or is something wrong?

**Comment by alex-jitbit** [comment]
From my experience some IdPs do support the passed URL. Like OneLogin for instance. Some support it when you modify it *slightly* (like add a directory to `http://hostname/` making it `http://hostname/directory`). Microsoft ignores everything completely. It depends.
