### ISSUE TITLE
Fortify

### ISSUE THREAD

**Issue by savy-creator** [jitbit/AspNetSaml#45]
Hi,
I would like to know how the following issue can be solved in the code.
Weak Encryption: Inadequate RSA Padding. Which was identified by Fortify during a security check. On the bold lines

Would it be to altogether use a different SignatureDescription.Or would Fortify have raised a false positive issue.

                 public override AsymmetricSignatureDeformatter CreateDeformatter(AsymmetricAlgorithm key)
		{
			if (key == null)
				throw new ArgumentNullException("key");

			**RSAPKCS1SignatureDeformatter deformatter = new RSAPKCS1SignatureDeformatter(key);
			deformatter.SetHashAlgorithm("SHA256");**
			return deformatter;
		}

**Comment by alex-jitbit** [comment]
I'm not sure this is our code
