### ISSUE TITLE
PasswordProtectedTransport, how to decode?

### ISSUE THREAD

**Issue by sseigneurin** [jitbit/AspNetSaml#52]
Hello,
I have an issue with an authentication request which is correctly decoded but after decryption gets something a PasswordProtectedTransport indication. The content remains impossible to read. Any idea on how to address this?

Example (some data hidden with *) of the decrypted SAML message:
 http://adfs.*******.eu/adfs/services/trusthttp://adfs.*******.eu/adfs/services/trusthSHXRpnAS1yYpTREl5oykz5bLz8/17Z8WzjlEU4T6cY=WWv4dq3Yqp82f5+zj+WDeDM0DlFZb9jYehbE2SftRbubq7e0kBzJ/JKeFTojfzR76OqM6FRbedetT/xYXOD3pLehvlHCkPSsRD0f8OIjGN6GS/kQvGEbvSYUitiDrmiNdd3hPZKgmHge0SWg2Rmps9mxuFLpSyNbj+AMmkphDwkxKG6EQBokZ+I+3WujhJfw98bvk3i0U6PRxw8BegmOMEo7Pyc54N11yqaJvzbgDzWhkDEcrW7e4u/XfzBY6WEoDJa0bmphYSlLVr+CU2B1M8r5azIy42VhjHsC/PdNDhrOGQobprnYRf51BUeMm3GTOQjSTNHIG4Yn6JGS4i1MlA==MIIC0jCCAbqgAwIBAgIQe5Z93GUk5aZEZ7b1uhHzuTANBgkqhkiG9w0BAQsFADAlMSMwIQYDVQQDExpBREZTIFNpZ25pbmcgLSBhZGZzLnNwYi5ldTAeFw0yMTAxMTIwOTA1MzZaFw0yMjAxMTIwOTA1MzZaMCUxIzAhBgNVBAMTGkFERlMgU2lnbmluZyAtIGFkZnMuc3BiLmV1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA09XH7h2FoFBIMF/lC6It7XJA2bjlGxJLgs3HfqNFl1nc9icXDdv6N/TKF/HOGUj/PH/GNkN709WI+eMQh0oeP0TAUMxeoZ9U6otMHOjpN+XL4wuaibS0/tKtYxQDfpvN7M2bS+YufANzJooqhrpnPMEo//RWu8ti6M2R/1B1QGlG99QQAVY8PC956ESHnwPi8/O/0FDhIZFAcHyR87QF7dGgk8m8zFj1S1EwKNjJ3Oe9SI9FbRh4EtAbZ7uHfbQz53Ody8qxFSfYEW98R+EvHKFUQwZ1/IC6eY1IlN3b+GQftMDvxC5olhVIxcz/0lhOgOnHEENYwEBxa3WJuRO0xQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBtFwxxoo+z2h7k90ssw6MTnJPyNFjUmxJWnrB7/Grj+cRd9I/IHDAY2KMP/9xgbjqmHtiI3tlizjK7wQZXT/Cn6RFd/xqNWufmqbJYyZ7i0DkmdK5veo+KhfHxxLS3DHeGrPE91b62FPiASd0yNPM2TTyd2XK2VHNiGTfEY9THFJHDcGol95whq7vrNYd+SiabJbvgWSWOFDLw2Wyj1tM47bB1uDwWagjBULGziRbefm9zNvxuhYiTcjSbrc05c/PqTLAhKFsOL3+ImnIVRJXkEuvKLG0jLC/DAHoU3/5vykkyuGM1mtYeCAZun8DTAchxl0Ge6XLMzB/3tgxkBJsMhttps://app.*******.**************Testurn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport 

Thanks.
Stéphane

**Comment by alex-jitbit** [comment]
Which variable did you get this from?

**Comment by sseigneurin** [comment]
Sorry, we finally managed to decode the content, there was another issue.
