### ISSUE TITLE
Assume expired as default

### ISSUE THREAD

**Issue by mnbeer** [jitbit/AspNetSaml#55]
In IsExpired(), it might be preferable to replace

`DateTime expirationDate = DateTime.MaxValue;`

with

`DateTime expirationDate = DateTime.MinValue;`

to assume expiration if a valid NotOnOrAfter is not located.

**Comment by alex-jitbit** [comment]
Please elaborate why would this be beneficial?

**Comment by mnbeer** [comment]
I realize that NotOnOrAfter is an optional element in the SAML 2 spec. However, I suspect that most implementations consider it mandatory (which is the case for in my situation). If mandatory, IsExpired should always return true if the DateTime.TryParse line is skipped because the "if" condition fails. Flipping from MaxValue to MinValue takes care of that.

Anyway, thanks for the code. It has been very useful.

**Comment by alex-jitbit** [comment]
This is a very powerful assumption and a breaking change.

I think that if the XML file _does not_ specify whether it should be expired, then the app should not make decisions for it.
