### ISSUE TITLE
How integrate on ASP.NET "old" framework

### ISSUE THREAD

**Issue by SimoneT88** [jitbit/AspNetSaml#58]
Hello, 
this is my first time working with SSO SAMIL 2.0.
I have a web application in ASP.NET "old" framework, I would like to understand how I can integrate SSO using saml.cs page.
I have a windows server 2019 and I do install and configure Service Provider Shibboleth

Can you give me some info to understand what I have to do?

Thank you

Hello

**Comment by alex-jitbit** [comment]
It's the same. The code form the Readme should work fine in a "classic" ASP.NET MVC application based on NET Framework.
