### ISSUE TITLE
samlCertificate 

### ISSUE THREAD

**Issue by sskrishnan9582** [jitbit/AspNetSaml#6]
Hi,
Where i can find my samlCertificate ?
I am getting error when it redirects to the application after login
System.Security.Cryptography.CryptographicException: Cannot find the requested object.

Please let me know.
thanks,
sri

**Comment by alex-jitbit** [comment]
Your SAML provider typically gives you one

**Comment by chtenb** [comment]
What do you mean by SAML provider? The Identity provider, or the Service provider?

**Comment by alex-jitbit** [comment]
@Chiel92 the identity provider
