### ISSUE TITLE
Certificate parsing of 'StringFromByteArray' is incorrect

### ISSUE THREAD

**Issue by admalledd** [jitbit/AspNetSaml#60]
per https://github.com/dotnet/runtime/issues/47005 

Using `Convert.FromBase64()`  instead of the method in `StringFromByteArray`

**Comment by alex-jitbit** [comment]
The problem is, certificate strings start with `---BEGIN CERTIFICATE---` which is not Base64, so it will throw errors

**Comment by alex-jitbit** [comment]
The issue mentioned provides a certificate in a different format that's the reason it does not work
