### ISSUE TITLE
Error on saml.cs file when install package using the nuget package manager

### ISSUE THREAD

**Issue by Sabin-Pradhan** [jitbit/AspNetSaml#64]
Hi,
I am trying to use saml for .net 3.5. I installed the package through the nuget package manager. After install package I get error of "CrytoConfig does not contain a definition to AddAlgorith "on below code

public static void Init()
		{
			if(!_initialized)
				CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
			_initialized = true;
		}

But if I copy the Saml.cs content from the github then the saml file content is totaly different. I am confused should I used the saml class that I get after package installation or the saml class showing in the github page.

**Comment by alex-jitbit** [comment]
The github version is more recent, please try it. We'll update Nuget shortly.

**Comment by Sabin-Pradhan** [comment]
Thanks for the response.
