### ISSUE TITLE
SignedXml CheckSignature issue

### ISSUE THREAD

**Issue by jhabjan** [jitbit/AspNetSaml#69]
For some reason CheckSignature  is always returning false.

This is where I get certificate from:

![jh-377](https://user-images.githubusercontent.com/6780815/202780821-dae11863-0fe7-465b-b00e-55b7e9df054b.png)

Only way I could get it working is to check the certificate I am receiving in the XML response from Azure:

![jh-375](https://user-images.githubusercontent.com/6780815/202779513-bfccfbd7-6dd6-442e-9e6f-7b9d9a044d89.png)

Is this right approach?

**Comment by alex-jitbit** [comment]
Yes, that's the right certificate link, it should look something like:
```
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
```

Not sure why it's not working, maybe you have your app connected more than once in Azure and you're using the wrong one?

**Comment by jhabjan** [comment]
Yep, that's what I have: 

![jh-379](https://user-images.githubusercontent.com/6780815/202796906-4c1afa96-d6fd-4172-ad35-2e8a1970a47d.png)

It's definitely only 1 application.

**Comment by alex-jitbit** [comment]
I would contact MS support and ask why the two certificates are different (in the Azure panel and the one they send with their repsonse)

**Comment by jhabjan** [comment]
Yes, perhaps I should do that.... 

Here is what I have... the one is downloaded from azure and the other pulled out from the xml response.

![jh-381](https://user-images.githubusercontent.com/6780815/202852594-af4d25a0-569c-4ec2-bc18-5980fb20855f.png)

**Comment by jaredthirsk** [comment]
@jhabjan I'm running into the same problem. Did you ever figure out what's going on?

**Comment by jaredthirsk** [comment]
I think I figured it out.   Instead of downloading from where you did, click the Edit in the top right and download from there instead.  Then my IsValid() is true for me:

![image](https://github.com/jitbit/AspNetSaml/assets/297187/27e836c2-448c-40b3-97a1-a73856e75e88)
