### ISSUE TITLE
SAML Response validation fails

### ISSUE THREAD

**Issue by kinjalhinguss** [jitbit/AspNetSaml#71]
I am getting the below error on **signedXml.CheckSignature(certificate, true)** line.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Security.Cryptography.Xml
  StackTrace:
   at System.Security.Cryptography.Xml.SignedXml.IsKeyTheCorrectAlgorithm(AsymmetricAlgorithm key, Type expectedType)

Can you please guide me on this?

**Comment by alex-jitbit** [comment]
I suggest you debug the code step by step and see which var is null exactly
