### ISSUE TITLE
Don't install by copying a file into the consuming project

### ISSUE THREAD

**Issue by atrauzzi** [jitbit/AspNetSaml#73]
The proper convention for doing a nuget packages is to compile it and then have those files be referenced.  Not by injecting a file into the consuming project.

This is particularly bad if for any reason your source file and/or its conventions do not 100% agree with the project you're forcing it into.

It also gives less experienced users a sense that they can modify the file, when really they can't and shouldn't (otherwise it defeats the purpose of having a package).

![image](https://user-images.githubusercontent.com/115199/213960103-de2ce891-453f-4a84-9766-ac58d3c907c4.png)

**Comment by alex-jitbit** [comment]
Fair point, this IS already in the works, actually. Hope to release this week.

**Comment by alex-jitbit** [comment]
https://www.nuget.org/packages/AspNetSaml/2.0.0-beta (pre release)
