### ISSUE TITLE
timezone changing

### ISSUE THREAD

**Issue by fatmazayedsayed** [jitbit/AspNetSaml#77]
in Egypt the time zone changed to be +3
we are running on saml login issue that it is not working after changing the timezone.
it gives me that error
and also the default login too
![image](https://user-images.githubusercontent.com/40010845/236688814-edc23609-ba58-4b00-827f-e68d33dd0082.png)

**Comment by alex-jitbit** [comment]
which URL gives the error?

**Comment by fatmazayedsayed** [comment]
@alex-jitbit 
our default  system home page is KB when i click on login or sign in button it gives that error
{websiteURL}/user/login
![image](https://user-images.githubusercontent.com/40010845/236756318-11b67665-ba77-4f6e-b691-088d27e2dfe3.png)

**Comment by alex-jitbit** [comment]
If this issue is related to the paid helpdesk app we're developing please submit a ticket at https://support.jitbit.com/
