### ISSUE TITLE
Not signed assembly

### ISSUE THREAD

**Issue by jtenciodev** [jitbit/AspNetSaml#78]
Hi, we require a signed (strong named) version of the AspNetSaml dll. We downloaded the nuget but assembly is not signed, is there a chance to get a version signed?

**Comment by alex-jitbit** [comment]
According to https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

**Comment by jtenciodev** [comment]
Yeah, however we are using it for .NET 4.6.1
