### ISSUE TITLE
NullPointerException: Method parameter 2 should not be null

### ISSUE THREAD

**Issue by rizamarhaban** [jitbit/AspNetSaml#8]
Hi,

I tested the Saml2 and it returns this:

```NullPointerException: Method parameter 2 should not be null; null parameters are not supported in orignal XML-RPC specs```

after redirecting to the endpoint. Any thoughts?

Many thanks.

**Comment by alex-jitbit** [comment]
Can you provide the full stack from the exception?

**Comment by alex-jitbit** [comment]
no response

**Comment by rizamarhaban** [comment]
@alex-jitbit sorry. I have resolved this. Thanks for closing the issue.
