### ISSUE TITLE
Error in SAML response - SignatureDescription could not be created for the signature algorithm supplied

### ISSUE THREAD

**Issue by vishnureddydotnet** [jitbit/AspNetSaml#80]
I am facing issue in samlResponse.IsValid() method. The code is breaking at this point 
return ValidateSignatureReference(signedXml) && signedXml.CheckSignature(_certificate, true) && !IsExpired();

The method signedXml.CheckSignature(_certificate, true) is returning an exception :
"SignatureDescription could not be created for the signature algorithm supplied."

The error is happening in IsValid() method in file Saml.cs (Line no- 74)

In The Saml response which we are getting in XmlDocument object there is a line:
ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>

But the link http://www.w3.org/2001/10/xml-exc-c14n# opens as a web page. Is that correct behavior?

What could be the possible cause of this and how to resolve this?
Please help. Thanks in advance.

**Comment by alex-jitbit** [comment]
Which .NET version?

**Comment by vishnureddydotnet** [comment]
> Which .NET version?
.NET version of our application is 4.6.1

**Comment by alex-jitbit** [comment]
Upgrading to at least 4.6.2 should resolve this
