### ISSUE TITLE
Logout Request

### ISSUE THREAD

**Issue by luizppuhl** [jitbit/AspNetSaml#85]
I'm having difficulties with the logout in saml does anyone have an example of how to do it?

**Comment by kamelabiad** [comment]
@luizppuhl how are you implementing the logout?

**Comment by AlperenLogo** [comment]
> I'm having difficulties with the logout in saml does anyone have an example of how to do it?

did you solve the logout problem ? If you did, how ?

**Comment by gauruv-grover** [comment]
This is the method I used for logout. 
`//Logout` method
public async Task<IActionResult> Logout()
{
    var samlEndpoint = _singleLogoutDestination; // Insert SSO Logout url here
    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    var request = new SignoutRequest(
        _issuer, //TODO: put your app's "entity ID" here
        _assertionConsumerServiceUrl //TODO: put Assertion Consumer URL (where the provider should redirect users after authenticating)
    );
    return Redirect(request.GetRedirectUrl(samlEndpoint));
}`

**Comment by dhavalcharadva-sf** [comment]
I did implemented logout code but it needs code change in SAML implementation becaues with current code is not working. I might create PR for this.

**Comment by saef-k** [comment]
@dhavalcharadva-sf how did you change the saml implementation for the logout?

**Comment by alex-jitbit** [comment]
fixed in 8fc8f1b195ade3f309f6d43afedc0139f1568d4c
