### ISSUE TITLE
'X509Certificate is immutable on this platform. Use the equivalent constructor instead.'

### ISSUE THREAD

**Issue by mayurbais** [jitbit/AspNetSaml#9]
Getting this error while trying to import the certificate:
Error: X509Certificate is immutable on this platform. Use the equivalent constructor instead.'

            cert = new X509Certificate2();
            cert.Import(certificate);

**Comment by CPavanKishore** [comment]
Hi @mayurbais  Did you integrated Saml in your Application...?

**Comment by WouterVanherck** [comment]
Try `cert = new X509Certificate2(certificate);` instead  
[As seen in the MSDN](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2(v=vs.110).aspx)

**Comment by alex-jitbit** [comment]
@mayurbais  What is the target platform you're building?

**Comment by iamsunny** [comment]
hi @mayurbais, did you find any solution to this error?

**Comment by alex-jitbit** [comment]
fixed

**Comment by srianbury** [comment]
What was the fix?

**Comment by alex-jitbit** [comment]
> What was the fix?

@srianbury see the commit link above
