### ISSUE TITLE
System.Formats.Asn1 8.0.0 contains vulnerabilities according to Checkmarx©

### ISSUE THREAD

**Issue by CenturySparkle** [jitbit/AspNetSaml#90]
Please update to latest dependencies to resolve vulnerabilities.

https://github.com/dotnet/announcements/issues/312

**Comment by petrzjunior** [comment]
@alex-jitbit Is it possible to create a new release with this fix? The current Nuget version (2.1.2) still contains the vulnerable dependencies.

**Comment by alex-jitbit** [comment]
@petrzjunior  just published all recent changes to nuget, should appear soon

**Comment by petrzjunior** [comment]
Thank you!
